[build]
  command = "hugo --gc --minify -D -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.142.0"
  # Remove these if not using theme as submodule
  # HUGO_THEMESDIR = "themes"
  # HUGO_THEME = "blowfish"